version: 2.1
 
orbs:
  android: circleci/android@0.2.1
 
jobs:
  build:
    executor: android/android
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x /submissions/gradlew
      - run:
          name: Download Dependencies
          command: /submissions/gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: /submissions/gradlew build
      - store_artifacts: 
          path: /submissions/app/build/reports
          destination: reports
      - run:
          name: Run Tests
          command: /submissions/gradlew lint test
      - store_test_results:
          path: /submissions/app/build/test-results
      - store_artifacts:  
          path: /submissions/app/build/outputs/apk/debug/
          destination: artifact-file